### PR TITLE
Bug squashing

### LINKED ISSUE #265: Regression - Metric json key should be "value" not "metric"

### LINKED ISSUE #266: Deal with 0-count substrings
The substringsCount can have members with `Count == 0`. I guess this happens when there are substrings that are suppressed. This is the cause of the following error. 

```
Explorer.ExplorerException: Error in column exploration for `Clinic` / `prescriptions` / `dosage`.
 ---> System.ArgumentOutOfRangeException: max must be > min! (Parameter 'max')
   at Explorer.Common.RandomExtensions.NextLong(Random random, Int64 min, Int64 max) in /build/src/explorer/Common/RandomExtensions.cs:line 18
   at Explorer.Components.TextGeneratorComponent.GenerateString(SubstringsData substrings, Int32 minLength, Random rand) in /build/src/explorer/Components/TextGeneratorComponent.cs:line 79
   at System.Linq.Enumerable.SelectRangeIterator`1.ToList()
   at Explorer.Components.TextGeneratorComponent.Explore() in /build/src/explorer/Components/TextGeneratorComponent.cs:line 71
   at Explorer.Components.ExplorerComponent`1.<get_ResultAsync>b__2_0() in /build/src/explorer/Components/ExplorerComponent.cs:line 10
   at Explorer.Components.TextGeneratorComponent.YieldMetrics()+MoveNext() in /build/src/explorer/Components/TextGeneratorComponent.cs:line 49
   at Explorer.Components.TextGeneratorComponent.YieldMetrics()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Explorer.Components.PublisherComponent.PublishMetrics(MetricsPublisher publisher) in /build/src/explorer/Components/PublisherComponent.cs:line 14
   at Explorer.Components.PublisherComponent.PublishMetrics(MetricsPublisher publisher) in /build/src/explorer/Components/PublisherComponent.cs:line 14
   at Explorer.ColumnExploration.<RunTask>b__13_0(Task t) in /build/src/explorer/ColumnExploration.cs:line 60
```

### PR DESCRIPTION
**Pull request by dandanlen**
- Rename "metrics" to "values" in json payload. 
- Handle suppressed substrings by returning a nullable string from the random string extractor, and use `*` as a placeholder in the generated string. 
- Prevent exception thrown on null dereference when datetime histogram is not generated. This just prevents the crash but doesn't fix the underlying problem. (see #267)

Fixes #265 
Fixes #266

### CODE REVIEW

File: src/explorer/Metrics/ExploreMetric.cs [hunk 1]
```diff
@@ -6,6 +6,7 @@ public interface ExploreMetric
     {
         public string Name { get; }
 
+        [JsonPropertyName("value")]
```
Comment (sebastian) [inline src/explorer/Metrics/ExploreMetric.cs:9]: Maybe this is also the time to add a shape related test? After all we had the right shape in the past, then suddenly didn't. Let's guard against this regression happening again.

Comment (dandanlen) [reply src/explorer/Metrics/ExploreMetric.cs:9]: 👍 it's on our list (#170). Now that the api is stabilized + versioned we'll prioritize this.
