### PR TITLE
Consider distinct values for min/max estimation.

### LINKED ISSUE #354: No metrics returned for some numerical columns
This happens when there is little useful data to be extracted - and causes the multicolumn correlation to fail. 

In these cases we ought to at least return the list of distinct values (if available). 

Sentry Issue: [EXPLORER-KQ](https://sentry.io/organizations/aircloak/issues/2004311248/?referrer=github_integration)

```
System.InvalidOperationException: Expected <descriptive_stats> metric of type Explorer.Components.NumericDistribution for column 'Line No_' but none was found.
  File "/workspaces/diffix-explorer/src/explorer/Queries/MultiColumn/MultiColumnScopeBuilder.cs", line 142, in TryGetMetric
  File "/workspaces/diffix-explorer/src/explorer/Queries/MultiColumn/MultiColumnScopeBuilder.cs", line 66, in <GetProjection>g__NumericProjection|6_0
  File "/workspaces/diffix-explorer/src/explorer/Queries/MultiColumn/MultiColumnScopeBuilder.cs", line 58, in GetProjection
  File "/workspaces/diffix-explorer/src/explorer/Queries/MultiColumn/MultiColumnScopeBuilder.cs", line 30, in Configure { <lambda> }
  File "/workspaces/diffix-explorer/src/explorer/ExplorationScope.cs", line 50, in MoveNext
...
(9 additional frame(s) were not displayed)

Error in MultiColumnExploration for NAV_W1_TENANT_WS001/SalesCrMemoLine/Document No_,Line No_.
```

### LINKED ISSUE #355: Text columns: some have common values others not
Take the `Addresses` table of the `Clinic` dataset.
The `province` columns lists distinct values, the `city` does not. Both clearly were able to produce some values.

The only difference is see is that one is considered categorical, the other not. Is that what causes this?

Bot should list some distinct values.

### PR DESCRIPTION
**Pull request by dandanlen**
In some cases min and max values aren't returned from the min and max sql
functions (returns null instead). This change adds a check for this and
uses the distinct values as backup to try to estimate a min and max.

This change also adds the distinct values metric to all result sets,
irrespective of whether the column is considered categorical or not.

I also replaced the generic `ILogger` with explicit `ILogger<T>` for
`ExploreComponent`s since the ILogger was not being correcly
injected by Lamar.

Fixes #354 
Fixes #355

### CODE REVIEW

File: src/explorer/Queries/MultiColumn/MultiColumnScopeBuilder.cs [hunk 1]
```diff
@@ -140,7 +140,7 @@ public T TryGetMetric<T>(string metricName)
                 catch (InvalidOperationException)
                 {
                     throw new InvalidOperationException(
-                        $"Expected <{metricName}> metric of type {typeof(T)} column {Column} but none was found.");
+                        $"Expected <{metricName}> metric of type {typeof(T)} for column '{Column}' but none was found.");
```
Comment (AndreiBozantan) [inline src/explorer/Queries/MultiColumn/MultiColumnScopeBuilder.cs:143]:
```suggestion
                        $"Expected '{metricName}' metric of type '{typeof(T)}' for column '{Column}' but none was found.");
```

**Review by AndreiBozantan — APPROVED** [review]
